
version: "3"

services:
  tcf-server:
    image: equipef/tcf-spring-backend
    container_name: server
    environment:
      - BANK_WITH_PORT=bank-system:9090
      - ISWUPLS_WITH_PORT=iswupls:8085
      - MAILSERVICE_WITH_PORT=mailservice:8090
      - POSTGRES_HOST=postgres:5432
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${POSTGRES_HOST} -- java -jar /opt/app/app.jar --bank.host.baseurl=http://$${BANK_WITH_PORT} --iswupls.host.baseurl=http://$${ISWUPLS_WITH_PORT}'"
    depends_on:
      - bank-system
      - postgres
      - iswupls
      - mailService
    ports:
      - "8080:8080"
  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres:
    image: postgres:15.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=tcf-db


  # A simple java CLI
  tcf-cli:
    image: equipef/tcf-spring-cli
    container_name: cli
    environment:
      - SERVER_WITH_PORT=tcf-server:8080
    entrypoint: "bash -c '/opt/app/wait-for-it.sh $${SERVER_WITH_PORT} -- java -jar /opt/app/app.jar'"
    depends_on:
      - tcf-server
    volumes:
      - ./cli/demo.txt:/opt/app/demo.txt
    stdin_open: true
    tty: true

  # An external bank service in NestJs
  bank-system:
    image: pcollet/tcf-bank-service
    container_name: bank

  # I saw where you parked last summer rust external service
  iswupls:
    image: equipef/rust_iswupls
    container_name: iswupls
    ports:
      - "8085:8085"

  # mail service rust external service
  mailService:
    image: equipef/rust_mailservice
    container_name: mailService
    ports:
      - "8090:8090"


