version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8000:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /opt/jdk17:/opt/java/openjdk

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "8001:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

volumes:
  jenkins_data:
  sonarqube_data: